server:
  port: 8080
  mode: "debug"
  read_timeout: 30s
  write_timeout: 30s

database:
  host: "localhost"
  port: 5432
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m

logging:
  level: "debug"
  format: "json"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Content-Type"
    - "Authorization"
    - "X-Requested-With"