version: 2

updates:
  # Go modules - Billing service
  - package-ecosystem: "gomod"
    directory: "/api/billing"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    assignees:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    commit-message:
      prefix: "deps(billing)"
      include: "scope"
    labels:
      - "dependencies"
      - "billing"
      - "go"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "github.com/lib/pq"
        update-types: ["version-update:semver-major"]

  # Go modules - Database migrations
  - package-ecosystem: "gomod"
    directory: "/api/billing-dbmigrations"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    assignees:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    commit-message:
      prefix: "deps(migrations)"
      include: "scope"
    labels:
      - "dependencies"
      - "migrations"
      - "go"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    assignees:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"

  # Docker base images
  - package-ecosystem: "docker"
    directory: "/api/billing"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    assignees:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "billing"

  - package-ecosystem: "docker"
    directory: "/api/billing-dbmigrations"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    reviewers:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    assignees:
      - "@gaetan-jaminon"  # Replace with actual GitHub username
    commit-message:
      prefix: "deps(docker)"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "migrations"