# Repository Configuration as Code
# This file defines repository settings, branch protection rules, and other policies
# Requires the Probot Settings app or manual application of these settings

repository:
  name: GoTuto
  description: "Go learning project with enterprise patterns - transitioning from .NET to Go"
  homepage: https://github.com/Gaetan-Jaminon/GoTuto
  topics:
    - go
    - golang
    - microservices
    - postgresql
    - openshift
    - ci-cd
    - learning
    - enterprise
    - dotnet-to-go
  private: false
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection rules
branches:
  - name: main
    protection:
      # Require pull request reviews before merging
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        require_last_push_approval: false
        bypass_pull_request_allowances:
          users: []
          teams: []

      # Require status checks to pass before merging
      required_status_checks:
        strict: true  # Require branches to be up to date before merging
        contexts:
          - "Continuous Integration"           # ci.yml workflow
          - "claude-review"                   # claude-code-review.yml workflow
          - "dependabot-check / dependabot-summary"  # dependabot-ci.yml workflow (if Dependabot PR)

      # Additional protection settings
      enforce_admins: false  # Allow repository admins to bypass protection (good for learning)
      allow_force_pushes: false
      allow_deletions: false
      block_creations: false
      required_linear_history: false
      
      # No restrictions on who can push (since it's a learning project)
      restrictions: null
      
      # Required conversation resolution before merging
      required_conversation_resolution: false

  - name: develop
    protection:
      # Lighter protection for development branch
      required_pull_request_reviews:
        required_approving_review_count: 0  # No required reviews for develop
        dismiss_stale_reviews: false
        require_code_owner_reviews: false

      # Still require CI to pass
      required_status_checks:
        strict: false  # Less strict for development
        contexts:
          - "Continuous Integration"

      enforce_admins: false
      allow_force_pushes: true   # Allow force pushes on develop for learning
      allow_deletions: false
      restrictions: null

# Labels for issue and PR management
labels:
  # Priority labels
  - name: "priority: high"
    color: "B60205"
    description: "High priority issue or PR"
  
  - name: "priority: medium"
    color: "FBCA04"
    description: "Medium priority issue or PR"
  
  - name: "priority: low"
    color: "0E8A16"
    description: "Low priority issue or PR"

  # Type labels
  - name: "type: bug"
    color: "D73A4A"
    description: "Something isn't working"
  
  - name: "type: feature"
    color: "0075CA"
    description: "New feature or request"
  
  - name: "type: documentation"
    color: "0052CC"
    description: "Improvements or additions to documentation"
  
  - name: "type: refactor"
    color: "5319E7"
    description: "Code refactoring"

  # Component labels
  - name: "component: billing"
    color: "C2E0C6"
    description: "Related to billing service"
  
  - name: "component: migrations"
    color: "C2E0C6"
    description: "Related to database migrations"
  
  - name: "component: ci/cd"
    color: "BFD4F2"
    description: "Related to CI/CD workflows"
  
  - name: "component: docs"
    color: "D4C5F9"
    description: "Related to documentation"

  # Learning labels
  - name: "learning: go-basics"
    color: "F9D0C4"
    description: "Learning Go fundamentals"
  
  - name: "learning: enterprise-patterns"
    color: "F9D0C4"
    description: "Learning enterprise Go patterns"
  
  - name: "learning: testing"
    color: "F9D0C4"
    description: "Learning Go testing patterns"

  # Dependencies
  - name: "dependencies"
    color: "8A2BE2"
    description: "Pull requests that update a dependency file"

# Issue templates and PR templates are handled by separate files in .github/
# This settings.yml focuses on repository-level configuration

# Security settings
security:
  enableVulnerabilityAlerts: true
  enableAutomatedSecurityFixes: true

# Merge settings
merge:
  allowSquashMerge: true
  allowMergeCommit: false
  allowRebaseMerge: true
  deleteBranchOnMerge: true

# Additional settings
features:
  issues: true
  projects: true
  wiki: false
  pages: false
  downloads: true