apiVersion: v1
kind: Namespace
metadata:
  name: billing-production
  labels:
    app.kubernetes.io/name: billing
    app.kubernetes.io/environment: production
    app.openshift.io/managed-by: github-actions
  annotations:
    openshift.io/description: "Billing Service - Production Environment"
    openshift.io/display-name: "Billing Production"