apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: billing
  labels:
    app: billing-api
    component: config
data:
  # Base configuration
  config.yaml: |
    server:
      port: 8080
      mode: release
      read_timeout: 10s
      write_timeout: 10s
      
    database:
      host: postgres-service
      port: 5432
      username: postgres
      name: billing
      ssl_mode: require
      max_open_conns: 100
      max_idle_conns: 10
      conn_max_lifetime: 5m
      
    logging:
      level: info
      format: json
      
    cors:
      allowed_origins:
        - "https://billing.apps.openshift.example.com"
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed_headers:
        - Content-Type
        - Authorization
      
    pagination:
      default_limit: 10
      max_limit: 100
      
  # Production overrides
  config.prod.yaml: |
    server:
      mode: release
      
    logging:
      level: warn
      
    cors:
      allowed_origins:
        - "https://billing.apps.openshift.example.com"
        - "https://api.example.com"