# Base configuration file
# This contains default values that can be overridden by environment-specific configs

server:
  port: 8080
  mode: debug # debug, release, test
  read_timeout: 30s
  write_timeout: 30s

database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  name: billing
  ssl_mode: disable
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m

logging:
  level: info # debug, info, warn, error
  format: json # json, text

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Content-Type
    - Authorization

pagination:
  default_limit: 10
  max_limit: 100
