# Development environment overrides

server:
  mode: debug
  
database:
  host: localhost
  
logging:
  level: debug
  format: text # easier to read in development
  
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://localhost:5173"
    - "http://localhost:8080"