# Production environment overrides

server:
  port: 8080
  mode: release
  read_timeout: 10s
  write_timeout: 10s
  
database:
  # These would typically come from environment variables or secrets
  # host: ${DB_HOST}
  # username: ${DB_USER}
  # password: ${DB_PASSWORD}
  ssl_mode: require
  max_open_conns: 100
  max_idle_conns: 10
  
logging:
  level: warn
  format: json
  
cors:
  allowed_origins:
    - "https://app.example.com"
    - "https://www.example.com"